IT WILL TAKE ALL OF YOUR ENERGY AND WILL TO BE ABLE TO WALK AGAIN.
A. TAKE
B. ALL
C. YOUR
D. ENERGY
THE WORKS OF MANY GREAT POETS HAVE BEEN PLACED ON RESERVE.
A. MANY
B. GREAT
C. PLACED
D. RESERVE
THE BROOKLYN BRIDGE WAS OPENED IN 1883.
A. BRIDGE
B. WAS
C. OPENED
D. IN
SPARTA AND ATHENS WERE ENEMIES DURING THE PELOPONNESIAN WAR.
A. AND
B. WERE
C. DURING
D. WAR
SHARKS AND LAMPREYS ARE NOT TRUE FISH BECAUSE THEIR SKELETONS ARE MADE OF CARTILAGE RATHER THAN BONE.
A. TRUE
B. BECAUSE
C. THEIR
D. BONE
JOE, HAVE YOU MET YOUR NEW BOSS?
A. HAVE
B. MET
C. YOUR
D. BOSS
SUE’S PARENTS TRIED LIVING IN THE NORTH, BUT THEY COULD NOT ADAPT TO THE COLD.
A. NORTH
B. BUT
C. NOT
D. ADAPT
MASTERING BASIC MATHEMATICS IS AN IMPORTANT GOAL FOR YOUNGER STUDENTS.
A. MASTERING
B. IMPORTANT
C. YOUNGER
D. STUDENTS
TO SEIZE A FOREIGN EMBASSY AND ITS INHABITANTS IS FLAGRANT DISREGARD FOR DIPLOMATIC NEUTRALITY.
A. SEIZE
B. ITS
C. FLAGRANT
D. NEUTRALITY
THE TROJANS’ RASH DECISION TO ACCEPT THE WOODEN HORSE LED TO THEIR DESTRUCTION.
A. THEIR
B. LED
C. ACCEPT
D. DESTRUCTION
SHERRY’S MOTHER ASKED _____NOT TO OPEN THE DOOR FOR STRANGERS.
A) HIM
B) HER
C) SOMEONE
D) ANYONE
_____IS A DEMONSTRATIVE PRONOUN.
A) EACH OTHER
B) MYSELF
C) IT
D) THIS
YOU ARE MY BEST FRIEND’ - WHICH ONE IS THE SUBJECT PRONOUN.
A) MY
B) ARE
C) YOU
D) FRIEND
MY BABY DROPPED HER HANKY ON THE GROUND’- WHICH ONE IS THE POSSESSIVE PRONOUN?
A) MY
B) HER
C) THE
D) ON
YOU MUST TRUST YOURSELF’ – WHICH ONE IS A REFLEXIVE PRONOUN?
A) YOU
B) MUST
C) YOURSELF
D) NONE OF THE ABOVE
LAURA WAS BORN IS FRANCE, BUT _______MOTHER WAS BORN IN GERMANY.
A) HIS
B) THEIR
C) HER
D) WHOSE
THESE ARE MY SISTERS _______NAMES ARE CATHY AND LINDA.
A) THERE
B) THEM
C) THEIR
D) HER
WHICH OF THE FOLLOWING IS AN INDEFINITE PRONOUN.
A) WHICH
B) ALL
C) MINE
D) WHOM
MY LAPTOP IS NOT WORKING. CAN I USE ______.
A) YOUR
B) IT
C) YOURS
D) THEIR
HE BLAMED ________FOR THE MISHAP.
A) HIMSELF
B) YOURSELF
C) THEMSELVES
D) WHOM
I REALLY LIKE WATCHING OLD SHOWS. _________ ARE SOME OF THE BEST THINGS ON TV.
A. THOSE
B. THAT
C. THIS
D. THESE
PLEASE HAND ME __________ .
A. THOSE
B. THAT
C. THIS
D. THESE
_________ IS SOME OF THE NICEST WEATHER WE’VE HAD LATELY.
A. THOSE
B. THAT
C. THIS
D. THESE
AFTER THE PARADE, __________ MET UP IN THE TOWN SQUARE.
A. SOMETHING
B. EVERYONE
C. ANYWHERE
D. SOMEWHER
WOULD YOU LIKE __________ TO DRINK.
A. SOMETHING
B. EVERYONE
C. ANYWHERE
I SEARCHED ALL OVER, BUT COULDN’T FIND MY NOTES __________ .
A. SOMETHING
B. EVERYONE
C. ANYWHERE
__________ FLAVOR DO YOU PREFER?
A. WHOM
B. WHICH
C. WHO
I HEARD SOMEONE AT THE DOOR BUT WASN’T SURE __________ IT WAS.
A. WHAT
B. WHICH
C. WHOM
__________ DO YOU WANT FOR LUNCH?
A. WHAT
B. WHICH
C. WHO
I SLIPPED ON THE SIDEWALK AND HURT _________ .
A. HIMSELF
B. THEMSELVES
C. MYSELF
THE KIDS RODE THE ROLLERCOASTER BY _________ .
A. THEMSELVES
B. HERSELF
C. HIMSELF
SHE BOUGHT _________ A NEW CAR.
A. HIMSELF
B. MYSELF
C. HERSELF
_________ AM LEARNING TO SPEAK BETTER ENGLISH.
A. I
B. ME
C. YOU
THANKS FOR THE PACKAGE! PLEASE LEAVE _________ ON THE TABLE.
A. THEM
B. THEM
C. IT
BEN WAS SURPRISED WHEN _________ DISCOVERED THAT HIS FRIENDS WERE HIDING IN THE LIVING ROOM.
A. SHE
B. HE
C. THEY
I LOST _________ PHONE LAST NIGHT.
A. MINE
B. MY
C. OURS
THEY BOUGHT NEW FURNITURE FOR _________ HOUSE.
A. MINE
B. THEIR
C. OURS
WE’RE GOING TO GET _________ TEST RESULTS TODAY.
A. MINE
B. YOURS
C. OUR
DAN AND I WAVED HELLO TO _________.
A. EACH OTHER
B. ONE ANOTHER
THE STUDENTS TALKED TO _________.
A. EACH OTHER
B. ONE ANOTHER
SALLY _________ TO THE PARK EVERY DAY.
A. RUN
B. RUNS
THE DOGS _________ AT STRANGERS.
A. BARK
B. BARKS
TED AND MARY _________ GOING TO THE MOVIES.
A. IS
B. ARE
THE GAME _________ (WAS, WERE) EXCITING.
A. WAS
B. WERE
THEY _________ TOO MUCH.
A. WORRY
B. WORRIES
SHE _________ EVERY NIGHT.
A. STUDY
B. STUDIES
BLACK OR WHITE _________ (IS, ARE) YOUR CHOICE.
A. IS
B. ARE
THAT _________ INCREDIBLE.
A. WAS
B. WERE
THOSE _________ PRETTY SHOES.
A. IS
B. ARE
THE CAT OR DOG _________ IN THE YARD.
A. IS
B. ARE

